### PR TITLE
improve gethistory

### PR DESCRIPTION
**Pull request by Pmant**
Always try to get one value before start and set its timestamp to start.
Could only test mysql, not sure if postrgresql, mssql and sqlite are working.

### CODE REVIEW

**Comment by Pmant** [comment]
http://forum.iobroker.net/viewtopic.php?f=24&t=2681

**Comment by GermanBluefox** [comment]
Can you leave real timestamp for the preFirst datapoint? Flot can hanlde this now and it will be interpolated for better drawing.

Can you add post last value request?

**Comment by Pmant** [comment]
I will add the post last value the same way I added the pre first and also keep both real timestamps.

But the problem with that is, every adapter or script using getHistory needs these workarounds with skipping older/newer values and interpolating etc. I think we need a solution where you can use getHistory and just get results you can work with. Maybe it would be better to do the whole preFirst/postLast/interpolation thing somewhere in the getHistory function(s) and/or the aggregate.js.

**Comment by Pmant** [comment]
#5

**Comment by GermanBluefox** [comment]
It is good point to implement preFirst/postLast/interpolation in the history. I will think about it.

**Pull request merged**
